version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/ollama:/root/.ollama
      - ./pull-model.sh:/usr/local/bin/pull-model.sh
      - ./models.txt:/models.txt

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    volumes:
      - ./volumes/open-webui:/app/backend/data
